apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-ft5z
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-ft5z
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-ft5z
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-ft5z
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-ft5z
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/push-pyxis-wmhx-tenant/appstudio/dc-metro-map-ft5z@sha256:f451a6065d9b9c6ab958a6f01e1d5376e169e675382e6f8e96e1c03c44543972
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 50m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 25Mi
status: {}
